[project]
name = 'Blockchain-Based-Inventory-Cycle-Counting-Automation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.auditor-verification]
path = 'contracts/auditor-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.counting-schedule]
path = 'contracts/counting-schedule.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
